version: '3.3'

services: 
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=kevin
            - MONGO_INITDB_ROOT_PASSWORD=123
            - MONGO_INITDB_DATABASE=admin
        ports: 
            - "27017:27017"